# config file version
apiVersion: 1

datasources:
  # <string, required> name of the datasource. Required
  - name: Prometheus
    type: prometheus
    isDefault: true
    url: http://prometheus:9090
